#!/usr/bin/env node
const rl = require('readline').createInterface({
  input: process.stdin,
  output: process.stdout
});

/**
 * Define the steps in our deployment. The user will be prompted before each step begins.
 */
const steps = [
  require('./upload-to-s3'),
  require('./git-push')
];

/**
 * Execute a series of steps, prompting the user for confirmation before taking any action.
 * Regardless of user input, all steps will be prompted.
 *
 * @param  {Array} steps  A list of steps, each containing a description and an action.
 * @return {void}
 */
function executeSteps(steps) {
  if (steps.length === 0) {
    rl.close();
    return process.exit();
  }

  const step = steps.shift();
  rl.question(`About to ${step.description}. Proceed? (y/n)  `, response => {
    const action = /^y(es)?$/i.test(response) ? step.action : callback => callback();
    action(() => executeSteps(steps));
  })
}

executeSteps(steps);
