#!/usr/bin/env node
require('dotenv').config();

const BUILD_DIR = 'dist';
const BUCKET = 'westonfribley.com';

const s3 = require('s3').createClient({
  s3Options: {
    accessKeyId: process.env.AWS_ACCESS_KEY_ID,
    secretAccessKey: process.env.AWS_SECRET_ACCESS_KEY,
    region: process.env.AWS_REGION
  }
});

const options = {
  localDir: BUILD_DIR,
  deleteRemoved: true,

  s3Params: {
    Bucket: BUCKET
  }
};

const uploader = s3.uploadDir(options);
console.log(`Deploying ${BUILD_DIR} to S3 bucket: ${BUCKET}`)

uploader.on('error', (err) => {
  console.error('Deployment failed', '\n', err);
  process.exit(1);
});

uploader.on('end', () => {
  console.log('Deployment succeeded!');
})
